Repository florentin-v/android-rpg-companion, pull requests merged in 2024-03, with the labels that each got.

#19 chore: improve coverage reporting
  .github/workflows/build_test_analyze_pr.yml
  app/build.gradle.kts
  app/src/main/kotlin/com/fvanaldewereld/rpgcompanion/navigation/RPGCompanionNavigation.kt
  app/src/main/kotlin/com/fvanaldewereld/rpgcompanion/ui/components/home/HomeScreen.kt
  app/src/main/kotlin/com/fvanaldewereld/rpgcompanion/ui/components/splashScreen/SplashScreen.kt
  build.gradle.kts
  common/src/main/kotlin/com/fvanaldewereld/rpgcompanion/common/ui/components/RpgCompanionTopAppBar.kt
  gradle/android_shared.gradle
  gradle/kover.gradle
  gradle/libs.versions.toml
  gradle/sonarqube.gradle
  scenario/scenario-ui-detail/src/main/kotlin/com/fvanaldewereld/rpgcompanion/ui/scenario/detail/components/ScenarioDetailLoading.kt
  scenario/scenario-ui-detail/src/main/kotlin/com/fvanaldewereld/rpgcompanion/ui/scenario/detail/components/ScenarioDetailSuccess.kt
  scenario/scenario-ui-list/src/main/kotlin/com/fvanaldewereld/rpgcompanion/ui/scenario/list/components/ScenarioListScreen.kt
Labels: CI/CD

#28 chore(github-actions): set up labeler
  .github/labeler_config.yml
  .github/workflows/labeler.yml
Labels: CI/CD

#27 chore(sonar): ignore code duplication in mock-factory
  README.md
  gradle/sonarqube.gradle
Labels: documentation

#24 feat: add icon and simplify splashscreen
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/ic_app_logo-playstore.png
  app/src/main/java/com/fvanaldewereld/rpgcompanion/navigation/NavigationRoute.kt
  app/src/main/java/com/fvanaldewereld/rpgcompanion/navigation/RPGCompanionNavigation.kt
  app/src/main/java/com/fvanaldewereld/rpgcompanion/ui/components/splashScreen/SplashScreen.kt
  app/src/main/res/animator/rotation.xml
  app/src/main/res/drawable/ic_app_logo_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_app_logo.webp
  app/src/main/res/mipmap-hdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-mdpi/ic_app_logo.webp
  app/src/main/res/mipmap-mdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_app_logo.webp
  app/src/main/res/mipmap-xhdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_logo.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_round.webp
  app/src/main/res/values/ic_app_logo_background.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: feature

#30 chore(docs): fix paths in README.md
  README.md
Labels: documentation

#36 chore: Dependency graph generation and added to README
  README.md
  app/build.gradle.kts
  build.gradle.kts
  documentation/dependency-graph/project.dot
  documentation/dependency-graph/project.dot.png
  documentation/dependency-graph/project.mermaid.md
  documentation/graph.png
  gradle/libs.versions.toml
  gradle/project_dependency_graph.gradle
Labels: documentation, dependencies

#43 chore: Improve ViewModel default parameter
  app/src/main/java/com/fvanaldewereld/rpgcompanion/navigation/RPGCompanionNavigation.kt
  scenario/scenario-ui-detail/src/main/java/com/fvanaldewereld/rpgcompanion/ui/scenario/detail/components/ScenarioDetailScreen.kt
  scenario/scenario-ui-list/src/main/java/com/fvanaldewereld/rpgcompanion/ui/scenario/list/components/ScenarioListScreen.kt
Labels: improvement

#54 fix: change dependency graph job scheduling
  .github/workflows/generate_dependency_graph.yml
  .pre-commit-config.yaml
  .scripts/pre-commit
  README.md
  build.gradle.kts
  docs/dependency-graph/project.dot
  docs/dependency-graph/project.dot.png
  docs/dependency-graph/project.mermaid.md
  gradle/git_hooks.gradle.kts
Labels: bug, documentation, dependencies

#53 feat: Support enableOnBackInvokedCallback
  app/src/main/AndroidManifest.xml
Labels: feature, improvement
